### ISSUE TITLE
The search component makes the page unresponsive when i click ⌘+K

### ISSUE THREAD

**Issue by JAYKALIA007** [karthikmudunuri/eldoraui#11]
The search component is breaking and making the page unresponsive when i try to access it via the shortcut. You can actually check the console where infinite number of uncaught errors are thrown regarding `HTMLElement.focus` .

Can I have a detailed look at the issue and try fixing this?

**Comment by karthikmudunuri** [comment]
yeah for sure @JAYKALIA007

**Comment by JAYKALIA007** [comment]
Have raised a PR for the same.
[fix for search shortcuts](https://github.com/karthikmudunuri/eldoraui/pull/17)

**Comment by karthikmudunuri** [comment]
<img width="920" alt="Screenshot 2024-08-01 at 7 34 16 PM" src="https://github.com/user-attachments/assets/b9d174c2-a94f-407d-92e2-623b11e25d95">
we have already deployed it.reopen the issue if u still have any
