### ISSUE TITLE
Multistep form

### ISSUE THREAD

**Issue by YanaTrifonova** [karthikmudunuri/eldoraui#12]
Font for email address is not visible

![Fullscreen_24_07_2024__10_38](https://github.com/user-attachments/assets/c4e8e6f5-6785-42f4-995e-59c6ad1f4448)

**Comment by karthikmudunuri** [comment]
@YanaTrifonova thank you for addressing the issue we will be fixing that issue by the EOD

**Comment by karthikmudunuri** [comment]
we have closed this issue kindly check
