### ISSUE TITLE
Deployment Issue

### ISSUE THREAD

**Issue by ESHAYAT102** [karthikmudunuri/eldoraui#19]
### Discussed in https://github.com/karthikmudunuri/eldoraui/discussions/18

<div type='discussions-op-text'>

<sup>Originally posted by **ESHAYAT102** August  5, 2024</sup>
### How Can I Deploy The Portfolio Template After Customizing It

I want to deploy the website with vercel. I tried to run `vercel` in the CLI, but it threw an error - `Error: Command "npm install" exited with 1`. I don't know what to do now. So, please help me out with this issue.</div>

**Comment by karthikmudunuri** [comment]
Try `npm install --legacy-peer-deps` for not getting any issues with dependencies versions. If u still get any error send me a ss
