### ISSUE TITLE
Form Component

### ISSUE THREAD

**Issue by Gandalf-hash** [karthikmudunuri/eldoraui#20]
**Describe the bug**
In Step 2, if input validation errors are triggered, the **Next** and **Prev** buttons are pushed downwards and hides the buttons from view, making it difficult to navigate to the next step.

**To Reproduce**
1. Navigate to step 2 in Form 
2. Try going to next step (step 3) without filling the fields
3. See error

**Expected behavior**
The **Next** and **Prev** buttons should remain visible and accessible at all times

Consider adjusting the height of the container holding the form UI (**make it scrollable if possible**) so that the **Next** and **Prev** buttons remain visible even when input errors are displayed.

**Screenshots**
![image](https://github.com/user-attachments/assets/4812a9b5-7e1f-48b3-bb18-a22f8261a241)
![image](https://github.com/user-attachments/assets/552670db-f7d3-442b-870c-4ad30ee0d02b)

**Comment by yogesh2104** [comment]
@Gandalf-hash remove py-12 from the form tag then working fine. for that, I am not creating a pull request.

**Comment by karthikmudunuri** [comment]
@Gandalf-hash @yogesh2104 will update it.
