### ISSUE TITLE
【Particles】Particles follow the mouse too fast

### ISSUE THREAD

**Issue by yaolifeng0629** [karthikmudunuri/eldoraui#23]
**Describe the bug**
The speed is normal for the first time. When the mouse is swiped, the particle moves quickly, which is the official increased default value
I tried to change staticity and ease to 10, but they did not take effect. The problem is still the same

**To Reproduce**
1. refresh website
2. move the mouse
3. Particles move very fast

**Expected behavior**
Like the official example, the speed is slow

**Screenshots**
![PixPin_2024-09-07_17-19-07](https://github.com/user-attachments/assets/15ba10f0-1ce2-4d52-a74f-cb2c5ac61fb2)

**Desktop (please complete the following information):**
 - OS: Window
 - Browser：Chrome
 - Version： 128.0.6613.120（正式版本） （64 位）

**Additional context**
![Clip_2024-09-07_17-24-33](https://github.com/user-attachments/assets/27c5d67a-7581-4b7a-b33a-43646b2a41c2)
![Clip_2024-09-07_17-24-55](https://github.com/user-attachments/assets/a359d4ed-b3e7-4140-bda9-28edc4001d6a)

**Comment by karthikmudunuri** [comment]
We have releases another version of EldoraUI where every issues are solved Kindly check it.
