### ISSUE TITLE
Review Comments Cut Off in "What People Are Saying" Section

### ISSUE THREAD

**Issue by Gandalf-hash** [karthikmudunuri/eldoraui#26]
### Description:
I have noticed that some reviews in the "**What People Are Saying**" section are being cut off, which prevents users from seeing the full comments. This can lead to misunderstandings and reduced user engagement, as potential users may not receive the complete feedback from previous users.

### Steps to Reproduce:
- Navigate to the "**What People Are Saying**" section of the library.
- Observe the reviews displayed.
- Identify any reviews that appear truncated or cut off.

### Expected Result:
- All reviews should display the full text, allowing users to access complete feedback.

### Screenshots:
![image](https://github.com/user-attachments/assets/fab7dfca-505c-4134-a67a-3007150eeda7)

**Comment by imran-yasin** [comment]
I started working on this.

**Comment by karthikmudunuri** [comment]
We have releases another version of EldoraUI where every issues are solved Kindly check it.
