### ISSUE TITLE
Getting a 404 page after clicking on the reload button

### ISSUE THREAD

**Issue by Niranjan-Baur** [karthikmudunuri/eldoraui#27]
**Describe the bug**
The issue "Getting a 404 page after clicking on the reload button" typically occurs when a user clicks the reload button in their browser while on a specific page, and instead of reloading the current content, the user is presented with a 404 error page (Page Not Found).

**To Reproduce**
Steps to reproduce the behaviour:
1. First open the site https://eldoraui.site/
2. Then open any animation like Cobeglobe, Globe anime, Bentogrid etc.
3. Then refresh/reload the page manually.
4. Then you can see the error.

**Expected behaviour**
When the user clicks the reload button on any page of the web application, the browser should reload the current content without displaying a 404 error. 

**Screenshots**

https://github.com/user-attachments/assets/a420b24e-0b60-4f63-8317-e16e183a6f88

**Desktop:**
 - Device : MacBook Pro
 - Browser : Chrome
 - Version : 129.0.6668

**Comment by karthikmudunuri** [comment]
it has been resolved
