### ISSUE TITLE
Getting a 403 page after clicking on the reload button

### ISSUE THREAD

**Issue by Niranjan-Baur** [karthikmudunuri/eldoraui#28]
**Describe the bug**
The issue "Getting a 403 page after clicking on the reload button" typically occurs when a user clicks the reload button in their browser while on a specific page, and instead of reloading the current content, the user is presented with a 403 error page (Forbidden).

**To Reproduce**
Steps to reproduce the behaviour:
1. First open the site https://eldoraui.site/components/
2. Then refresh/reload the page manually.
3. Then you can see the error.

**Expected behaviour**
When the user clicks the reload button on any page of the web application, the browser should reload the current content without displaying a 403 error. 

**Screenshots**

https://github.com/user-attachments/assets/79346b1e-5cf0-435a-9670-73b2ef85774a

**Desktop:**
 - Device : MacBook Pro
 - Browser : Chrome
 - Version : 129.0.6668

**Comment by karthikmudunuri** [comment]
once check it again.i think that issue has been solved

**Comment by karthikmudunuri** [comment]
thank you for telling this issue to me.ill work on this asap

**Comment by karthikmudunuri** [comment]
it has been resolved
