### ISSUE TITLE
Text animation -> Typing Effect docs issue

### ISSUE THREAD

**Issue by deepumandal** [karthikmudunuri/eldoraui#29]
**Describe the bug**

**To Reproduce**
1. visit the site below attached link
https://www.eldoraui.site/components/text/typingeffect

**Expected behavior**
In Step 2, some content is missing.

**Screenshots**
![image](https://github.com/user-attachments/assets/5a99ac9b-6316-4046-a172-659956141469)

**Comment by karthikmudunuri** [comment]
We have releases another version of EldoraUI where every issues are solved Kindly check it.
