### ISSUE TITLE
The icon may be copyrighted

### ISSUE THREAD

**Issue by kishaningithub** [karthikmudunuri/eldoraui#3]
The icon being used for this project looks very similar to IntelliJ IDE icon which is owned by Jetbrains company

**Comment by karthikmudunuri** [comment]
> The icon being used for this project looks very similar to IntelliJ IDE icon which is owned by Jetbrains company

Will be working on it to make a new one.

**Comment by karthikmudunuri** [comment]
kindly check we updated the logo

**Comment by kishaningithub** [comment]
Looks similar to the old.. guess it's fine

**Comment by karthikmudunuri** [comment]
@kishaningithub a designer is working on logo until then we are using this
