### ISSUE TITLE
Allow drag and drop in bento compnent.

### ISSUE THREAD

**Issue by SaiSawant1** [karthikmudunuri/eldoraui#30]
**Is your feature request related to a problem? Please describe.**
I really like what you guys have done with the bento grid, it looks cool. 
I got to know about the library because I was looking for a bento component however your current implementation doesn't have a drag-and-drop feature.

**Describe the solution you'd like**
If you allow I would love to implement drag and drop into your bento component.

[something like this](https://www.joshuabrigati.com/?ref=dailydev)

**Describe alternatives you've considered**

**Additional context**

**Comment by karthikmudunuri** [comment]
We have releases another version of EldoraUI where every issues are solved Kindly check it. and also a nice idea for a component will start working on it.
