### ISSUE TITLE
[bug]: /docs/components/animatedborderbutton  has no animation

### ISSUE THREAD

**Issue by Snazzie** [karthikmudunuri/eldoraui#31]
**Describe the bug**
No animation on animated border button example

**To Reproduce**
1. hover over button
2. no border animation

**Expected behavior**
expect button to have animated border on hover

**Screenshots**

**Desktop (please complete the following information):**
 - OS: windows
 - Browser: edge
 - Version: ..

**Comment by karthikmudunuri** [comment]
Thanks for bringing it to our notice we will solve it ASAP

**Comment by karthikmudunuri** [comment]
The issue has been fixed Kindly check it from here: https://www.eldoraui.site/docs/components/animatedborderbutton
