### ISSUE TITLE
Progress slider: Layout gets broken when fast-clicking through different items

### ISSUE THREAD

**Issue by elussich** [karthikmudunuri/eldoraui#7]
Hello! First of all, thanks for open-sourcing this incredible library; looks super neat and useful.

This particular issue happens when fast-clicking through the different items on the **Progress slider** component. I'm attaching a small video to showcase the behavior:

https://github.com/user-attachments/assets/b27ad0e3-6448-4130-b6ef-ce891021e2c6.mov

As you see, the layout gets scrambled when clicking around the items real fast, and only gets reestablished once the timer for a given item is complete. The issue is consistent and easy to reproduce.

I just came across your library today, and already been browsing the different components; it looks _great_.
I couldn't get the time to dig deeper into the issue, but I would be more than happy to give it a try.

Let me know if you have any other questions or details you may need.
Thank you again! 🙏

**Comment by karthikmudunuri** [comment]
@elussich sorry for that and we will fix this ASAP and thanks a lot for finding the issue and for supporting us.

**Comment by karthikmudunuri** [comment]
@elussich we have rechecked the component u provided the reason why it is getting scrambled bcoz of the height of the componentpreview in that page.u can check by installing the component it works well if u integrate in your project.we will fix that bug by tomorrow but the component is working well if u installed it.

https://github.com/user-attachments/assets/e75d1b65-8d40-4b6c-8624-89d8f171769f


u can reopen the issue if u still find any difficulties.

**Comment by elussich** [comment]
Thank you!
