### ISSUE TITLE
Tag Components Page isn't working

### ISSUE THREAD

**Issue by FranzAbsalon** [karthikmudunuri/eldoraui#9]
This is displayed whenever I go with the Tag Component:

- Application error: a client-side exception has occurred (see the browser console for more information).

Here's in the console:

- Error: Error creating WebGL context.

**Comment by karthikmudunuri** [comment]
we haven't found any issue regarding that make sure u created .jsx file.

https://github.com/user-attachments/assets/e51121e2-b0c2-4233-8932-1127272dd131

u can reopen the issue again iff u still facing the issue
